export default function AboutPage() {
  return (
    <div style={{ minHeight: '100svh', background: '#f5f5f3' }}>

      {/* Header */}
      <header style={{ background: '#ffffff', borderBottom: '1px solid #e5e7eb' }}>
        <div style={{ maxWidth: 680, margin: '0 auto', padding: '14px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <a href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
            <div style={{
              width: 26, height: 26, borderRadius: 6, background: '#111',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round">
                <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
                <polyline points="16 7 22 7 22 13" />
              </svg>
            </div>
            <span style={{ fontSize: 14, fontWeight: 700, color: '#111', letterSpacing: '-0.02em' }}>
              buzzd.fyi
            </span>
          </a>
          <a href="/" style={{ fontSize: 13, color: '#6b7280', textDecoration: 'none' }}>← Back</a>
        </div>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 680, margin: '0 auto', padding: '48px 24px 80px' }}>

        <h1 style={{ fontSize: 28, fontWeight: 700, color: '#111', letterSpacing: '-0.03em', marginBottom: 8 }}>
          About buzzd.fyi
        </h1>
        <p style={{ fontSize: 13, color: '#9ca3af', marginBottom: 48 }}>Last updated June 2026</p>

        {/* What it is */}
        <section style={{ marginBottom: 40 }}>
          <h2 style={h2}>What this is</h2>
          <p style={body}>
            buzzd.fyi is a free, read-only tool that tracks which stocks are being discussed most on Reddit — across communities like r/wallstreetbets, r/stocks, and r/investing. It surfaces mention volume, community sentiment, and AI-generated analysis of why a stock is trending.
          </p>
          <p style={{ ...body, marginTop: 12 }}>
            It is a signal aggregator, not a trading platform. It does not execute trades, manage money, or provide personalized investment recommendations.
          </p>
        </section>

        {/* NOT financial advice — the important one */}
        <section style={{ marginBottom: 40, background: '#fff8f0', border: '1px solid #fed7aa', borderRadius: 10, padding: '20px 24px' }}>
          <h2 style={{ ...h2, color: '#c2410c' }}>Not financial advice</h2>
          <p style={body}>
            <strong>Nothing on buzzd.fyi is financial, investment, tax, or legal advice.</strong> The information presented — including sentiment scores, trend predictions, mention counts, and AI-generated analysis — is for informational and entertainment purposes only.
          </p>
          <p style={{ ...body, marginTop: 12 }}>
            Predictions shown on this site are generated by an AI model analyzing Reddit post volume and sentiment. They are not based on fundamental analysis, earnings data, insider information, or any professional research methodology. They can and will be wrong.
          </p>
          <p style={{ ...body, marginTop: 12 }}>
            <strong>Do not make any financial decision based on what you read here.</strong> Before buying or selling any security, consult a licensed financial advisor who understands your personal financial situation, goals, and risk tolerance.
          </p>
        </section>

        {/* Accuracy */}
        <section style={{ marginBottom: 40 }}>
          <h2 style={h2}>No guarantees of accuracy</h2>
          <p style={body}>
            buzzd.fyi makes no warranties, express or implied, regarding the accuracy, completeness, timeliness, or reliability of any information displayed. Reddit data is inherently noisy — posts can be spam, coordinated manipulation, satire, or fiction. AI sentiment analysis can misread context, sarcasm, and irony.
          </p>
          <p style={{ ...body, marginTop: 12 }}>
            Past discussion volume and community sentiment have no proven predictive relationship with future stock price movement. Stocks mentioned frequently on Reddit have historically exhibited extreme volatility in both directions.
          </p>
        </section>

        {/* Liability */}
        <section style={{ marginBottom: 40 }}>
          <h2 style={h2}>Limitation of liability</h2>
          <p style={body}>
            To the fullest extent permitted by law, buzzd.fyi and its operators shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of this site or reliance on any information presented here — including but not limited to financial losses, lost profits, or investment decisions made based on content displayed on this platform.
          </p>
          <p style={{ ...body, marginTop: 12 }}>
            By using this site, you acknowledge that you understand and accept these limitations.
          </p>
        </section>

        {/* Data sources */}
        <section style={{ marginBottom: 40 }}>
          <h2 style={h2}>Data sources</h2>
          <p style={body}>
            Stock discussion data is sourced from Reddit's public API. buzzd.fyi is not affiliated with, endorsed by, or sponsored by Reddit, Inc. Reddit is a trademark of Reddit, Inc.
          </p>
          <p style={{ ...body, marginTop: 12 }}>
            Stock tickers and company names are used for identification purposes only. buzzd.fyi is not affiliated with any of the companies whose securities may appear on this site.
          </p>
        </section>

        {/* Contact */}
        <section>
          <h2 style={h2}>Contact</h2>
          <p style={body}>
            Questions or concerns? Reach out at{' '}
            <a href="mailto:hello@buzzd.fyi" style={{ color: '#111', fontWeight: 500 }}>hello@buzzd.fyi</a>.
          </p>
        </section>

      </main>
    </div>
  );
}

const h2: React.CSSProperties = {
  fontSize: 15,
  fontWeight: 700,
  color: '#111',
  letterSpacing: '-0.01em',
  marginBottom: 10,
};

const body: React.CSSProperties = {
  fontSize: 14,
  color: '#374151',
  lineHeight: '1.7',
  margin: 0,
};
